version: 2

jobs:
  build:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - restore_cache: # special step to restore the dependency cache
          key: dependency-cache-v1-{{ checksum "package.json" }}
      - run:
          name: NPM install
          command: npm install
      - run:
          name: Check build
          command: npm run build
      - run:
          name: Run tests
          command: npm run test:ci
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-v1-{{ checksum "package.json" }}
          paths:
            - ./node_modules

  publish:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: Add token to .npmrc
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - run:
          name: NPM install
          command: npm install
      - run:
          name: Set up git user
          command: |
            git config user.email "azhivaeva@flo.team"
            git config user.name "azhivaeva-flo"
      - run:
          name: Run tests
          command: npm run test:ci
      - run:
          name: Bump version
          command: |
            GIT_COMMIT_DESC="$(git log --format=oneline -n 1 $CIRCLE_SHA1)"
            echo "${GIT_COMMIT_DESC}"

            MINOR="Merge pull request.+minor"
            if [[ "${GIT_COMMIT_DESC}" =~ $MINOR ]]; then
              "$(npm version minor -m "chore: version %s [ci skip]")
            else
              "$(npm version patch -m "chore: version %s [ci skip]")
            fi
      - run:
          name: Prepublish
          command: npm run prepublishOnly
      - run:
          name: Publish
          command: |
            VERSION=$(cat package.json \
              | grep version \
              | head -1 \
              | awk -F: '{ print $2 }' \
              | sed 's/[",]//g' \
              | tr -d '[[:space:]]')

            npm publish "./dist/floteam-errors-${VERSION}.tgz" --access public
      - run:
          name: Git Push
          command: |
            git push origin ${CIRCLE_BRANCH}
            git push origin --tags

workflows:
  version: 2
  build_and_publish:
    jobs:
      - build:
          filters:
            branches:
              ignore: /^master$/
      - publish:
          filters:
            branches:
              only:
                - master
          context: NPM_TOKEN
